[config]
reload_apps = true
set_wallpaper = true
wallpaper_tool = 'Swww'
prefix = '@'
swww_options = [
    "--transition-type",
    "center",
]
run_after = [
    [ "echo", "'hello'" ],
    [ "echo", "'hello again'" ],
]

[config.reload_apps_list]
kitty = true
# gtk_theme = true
hyprland = true

[templates.hyprland]
input_path = '~/.config/matugen/hyprland-colors.conf'
output_path = '~/.config/hypr/conf/colors.conf'

[templates.kitty]
input_path = '~/.config/matugen/kitty-colors.conf'
output_path = '~/.config/kitty/colors.conf'

[templates.walogram]
input_path = '~/.config/matugen/walogram.conf'
output_path = '~/.cache/walogram/colors.conf'

# [templates.gtk3]
# input_path = '~/.config/matugen/gtk-colors.css'
# output_path = '~/.config/gtk-3.0/gtk.css'
#
# [templates.gtk4]
# input_path = '~/.config/matugen/gtk-colors.css'
# output_path = '~/.config/gtk-4.0/colors.css'
