# ----------------------------------------------------- 
# Monitor Setup
# See https://wiki.hyprland.org/Configuring/Monitors/
# ----------------------------------------------------- 

monitor=eDP-1,1920x1080,0x0,1
monitor=DP-4,1920x1080@120,1920x0,1
monitor=DP-1,2560x1440,3840x0,1
