# ----------------------------------------------------- 
# Window rules
# ----------------------------------------------------- 

windowrule = float,^(pavucontrol)$
windowrule = opacity 1.0 override 1.0 override,(jetbrains-pycharm-ce)

windowrulev2 = workspace 1,class:^(.*telegram.*)$
windowrulev2 = workspace 1,class:^(Mattermost)$
windowrulev2 = workspace 2,class:^(.*pycharm.*)$
windowrulev2 = workspace 2,class:^(.*[Aa]pex.*)$,fullscreen
windowrulev2 = workspace 3,class:^(.*Nautilus)$
windowrulev2 = workspace 3,class:^(.*Meld)$
windowrulev2 = workspace 4,class:^(yaamp)$
windowrulev2 = workspace 4,class:^(evolution)$
windowrulev2 = workspace 5,class:^(Yandex-browser)$
